config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user
  before_action :authorized_profile, only: [:edit, :update]

  def show
    @posts = @user.posts.includes(:comments)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(profile_params)
        format.html { redirect_to profile_path(@user.user_name), flash: { success: 'Profile was successfully updated.' }  }
      else
        flash[:error] = @user.errors.full_messages
        format.html { render :edit }
      end
    end
  end

  private

    def set_user
      @user = User.find_by(user_name:  params[:user_name])
    end

    def authorized_profile
      unless current_user == @user
        redirect_to profile_path(@user.user_name), flash: { alert: 'You are not authorized to edit this profile.'}
      end
    end

    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def profile_avatar_select user
    if user.avatar?
      return image_tag user.avatar.url, id: 'image-preview', class: 'img-responsive img-circle profile-image'
    end

    image_tag 'default-avatar.png', id: 'image-preview', class: 'img-responsive img-circle profile-image'
  end

end

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: { action: 'update' }, html: { multipart: true} do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your avatar:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange: 'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Your bio:
                = f.text_area :bio, label: false, rows: 4, class: 'form-control'
          .form-group.text-center
            = f.submit 'Edit Profile', class: 'btn btn-success'
      .text-center
        = link_to 'Go Back', profile_path(@user.user_name)
        \|
        = link_to 'Posts', root_path
      %p

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button'
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'

-@posts.each do |post|
  = render 'posts/post', post: post