config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  caption    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image      :string(255)
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_5b5ddfd518  (user_id => users.id)
#

class Post < ApplicationRecord

  default_scope { order('posts.created_at DESC') }

  acts_as_votable

  mount_uploader :image, PostImageUploader

  # Assocciations
  belongs_to :user
  has_many :comments, dependent: :destroy

  # Validations
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :authorize_posts, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user, :comments).all.page(params[:page])
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, flash: { success: 'Post was successfully created.' } }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(@post), flash: { success: 'Post was successfully updated.' } }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.'}
    end
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def authorize_posts
      unless current_user == @post.user
        redirect_to root_path, flash: { alert: 'You are not authorized to edit this post.'}
      end
    end

    def post_params
      params.require(:post).permit(:caption, :image)
    end

end

app/helpers/posts_helper.rb
module PostsHelper

  def form_image_select(post)
    return image_tag post.image.url, id: 'image-preview', class: 'img-responsive' if post.image?
    image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end

  def liked_post(post)
    if current_user.voted_for? post
      return 'glyphicon-heart'
    end

    'glyphicon-heart-empty'
  end

  def display_likes_for(post)
    votes = post.votes_for.up.by_type('user') # get the likes by users
    if votes.size <= 8
      return likers_list(votes)
    end

    count_likers(votes)
  end

  private

    def likers_list(votes)
      user_names = []

      unless votes.blank?
        votes.voters.each do |voter|
          user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
        end

        user_names.to_sentence.html_safe + like_plural(votes)
      end
    end

    def count_likers(votes)
      vote_count = votes.size
      vote_count.to_s + ' likes'
    end

    def like_plural(votes)
      if votes.count > 1
        return ' like this'
      end

      ' likes this'
    end

end

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, :html => { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, as: :file
            .form-group.text-center
              = f.input :caption
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.haml
.likes{ id: "likes_#{post.id}" }
  = display_likes_for post

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url, class: 'img-responsive'), post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            = link_to post.user.user_name, profile_path(post.user.user_name)
          = post.caption
        .comments{ id: "comments_#{post.id}" }
          - if post.comments.any?
            .paginator{ id: "#comments-paginator-#{post.id}" }
              - unless post.comments.count <= 4
                = link_to "View all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: { post_id: "#{post.id}", type: 'html' }
            / render post.comments.last(4), post: post
    .row
      .comment-like-form
        .like-button.col-sm-1
          = link_to '', like_post_path(post.id),remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post post}"
        .comment-form.col-sm-11
          = form_for([post, post.comments.new]) do |f|
            = f.text_field :body, placeholder: 'Leave a comment...', id: "comment_content_#{post.id}", class: 'comment_content'
            = f.submit 'New Comment', class: 'comment-submit-button'

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }
  \|
  = link_to 'Go Back', posts_path

app/views/posts/index.html.haml
#posts
  = render 'posts'
#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");

if (!$('#load_more').length) { 
  $('#paginator').remove(); 
}

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render 'form'
.text-center.edit-links
  = link_to 'Go Back', posts_path

app/views/posts/show.html.haml
.row
  = render 'post', post: @post
  .text-center.edit-links
    -if @post.user == current_user
      = link_to 'Edit', edit_post_path(@post)
      \|
      = link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
      \|
    = link_to 'Go Back', posts_path